[package]
name = "Homomorphic_Operations_on_8_bit_Integers_with_Optimized_Arithmetic_and_Comparison_using_TFHE"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "x86_64"] }

